name: "DotNet - Deploy"

on:
  workflow_dispatch:
     inputs:
      basic-tests:
        description: Basic tests
        type: boolean
        required: false
        default: true
      generic-tests:
        description: Generic tests
        type: boolean
        required: false
        default: true

env:
  DRIVER_PATH: /usr/bin
  APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
  APPLITOOLS_API_KEY_READ: ${{ secrets.APPLITOOLS_API_KEY_READ }}
  SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
  SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
  CORE_VERSION: "3.3.1"

jobs:

  dotnet-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0"
      - name: Run Selenium coverage tests
        shell: pwsh
        run: |
          cd dotnet
          ./download_cores.ps1
          ./update_core_versions.ps1
          ./update_versions.ps1
          chmod +x ./deploy.sh && ./deploy.sh
          chmod +x ./sendMail.sh && ./sendMail.sh