name: Build and test python packages
on:
  schedule: [cron: 42 3 * * *]
  workflow_dispatch:
    inputs:
      pytest_filter:
        description: Execute only tests with names containing this substring
        type: string
        required: false
      unit_tests:
        description: Unit tests
        type: boolean
        required: false
        default: true
      installation_tests:
        description: Installation tests
        type: boolean
        required: false
        default: false
      generated_tests:
        description: Generated tests
        type: boolean
        required: false
        default: false
      functional_tests:
        description: Functional tests
        type: boolean
        required: false
        default: false
      robotframework_tests:
        description: Robot framework tests
        type: boolean
        required: false
        default: false
  workflow_call:
    inputs:
      ref:
        description: branch to test
        required: false
        type: string
      releasing_package:
        description: name of the package being released
        required: false
        type: string
      # Same parameters as workflow_dispatch, run all tests by default
      pytest_filter:
        description: Execute only tests with names containing this substring
        required: false
        type: string
      unit_tests:
        description: Unit tests
        type: boolean
        required: false
        default: true
      installation_tests:
        description: Installation tests
        type: boolean
        required: false
        default: true
      generated_tests:
        description: Generated tests
        type: boolean
        required: false
        default: true
      functional_tests:
        description: Functional tests
        type: boolean
        required: false
        default: true
      robotframework_tests:
        description: Robot framework tests
        type: boolean
        required: false
        default: true

env:
  RELEASING_PACKAGE: ${{ inputs.releasing_package }}
  BONGO_REPORT_TESTS: true
  PYTEST_FILTER: ${{ inputs.pytest_filter }}

jobs:
  dist-build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{inputs.ref || github.ref}}
      - uses: actions/setup-python@v4
        with:
          python-version: "3.6"
      - name: Build packages
        working-directory: python
        run: make dist
      - uses: actions/upload-artifact@v3
        with:
          name: packages
          if-no-files-found: error
          # the * wildcard in pyth*n is not to match anything, but to prevent
          # upload-artifact from flattening python directory, e.g. uploading
          # its contents without python directory itself.
          path: "pyth*n/*/dist/"

  unit-tests:
    needs: dist-build
    if: ${{ !(github.event_name == 'workflow_dispatch') || inputs.unit_tests }}
    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-latest, windows-latest ]
        python-version: [ '2.7', '3.6', '3.11' ]
        exclude:
          - os: macos-latest
            python-version: '2.7'
          - os: macos-latest
            python-version: '3.6'
          - os: windows-latest
            python-version: '2.7'
          - os: windows-latest
            python-version: '3.6'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{inputs.ref || github.ref}}
      - if: matrix.python-version == '2.7'
        run: sudo apt-get --yes install python2 virtualenv && virtualenv --python python2 --download venv
        working-directory: python
      - if: matrix.python-version != '2.7'
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/download-artifact@v3
        with:
          name: packages
      - name: make unit_tests
        shell: bash
        run: |
          [ ${{ matrix.python-version }} = 2.7 ] && source venv/bin/activate
          make unit_tests
        working-directory: python
        env:
          BONGO_REPORT_TESTS: false

  unit-tests-alpine:
    needs: dist-build
    if: ${{ !(github.event_name == 'workflow_dispatch') || inputs.unit_tests }}
    runs-on: ubuntu-20.04
    container: "alpine:latest"
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{inputs.ref || github.ref}}
      - uses: actions/download-artifact@v3
        with:
          name: packages
      - run: apk add gcc libffi-dev make musl-dev py3-pip python3-dev
      - run: make unit_tests
        working-directory: python
        env:
          BONGO_REPORT_TESTS: false

  unit-tests-linux-arm64:
    needs: dist-build
    if: ${{ !(github.event_name == 'workflow_dispatch') || inputs.unit_tests }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{inputs.ref || github.ref}}
      - uses: actions/download-artifact@v3
        with:
          name: packages
      - uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          distro: ubuntu18.04
          githubToken: ${{ github.token }}
          install: |
            set -e
            apt-get update
            apt-get install --no-install-recommends -y ca-certificates curl gcc make python3-dev
            ln -s `which python3` /usr/local/bin/python
            curl -O https://bootstrap.pypa.io/pip/3.6/get-pip.py
            python get-pip.py
            pip config --user set global.progress_bar off
          run: make --directory=python unit_tests
          env: | # YAML, pipe character is necessary
            BONGO_REPORT_TESTS: false

  installation-tests:
    needs: dist-build
    if: ${{ !(github.event_name == 'workflow_dispatch') || inputs.installation_tests }}
    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-latest, windows-latest ]
        python-version: [ '2.7', '3.11' ]
        exclude:
          - os: macos-latest
            python-version: '2.7'
          - os: windows-latest
            python-version: '2.7'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{inputs.ref || github.ref}}
      - if: matrix.python-version == '2.7'
        run: sudo apt-get --yes install python2 virtualenv && virtualenv --python python2 --download venv
        working-directory: python
      - if: matrix.python-version != '2.7'
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/download-artifact@v3
        with:
          name: packages
      - name: make eyes_selenium_installation_tests
        shell: bash
        run: |
          [ ${{ matrix.python-version }} = 2.7 ] && source venv/bin/activate
          make eyes_selenium_installation_tests
        working-directory: python

  generated-tests-images:
    needs: dist-build
    if: ${{ !(github.event_name == 'workflow_dispatch') || inputs.generated_tests }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{inputs.ref || github.ref}}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/download-artifact@v3
        with:
          name: packages
      - run: make eyes_images_generated_tests
        working-directory: python
        env:
          APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
          APPLITOOLS_API_KEY_READ: ${{ secrets.APPLITOOLS_API_KEY_READ }}


  generated-tests-appium:
    needs: dist-build
    if: ${{ !(github.event_name == 'workflow_dispatch') || inputs.generated_tests }}
    concurrency: sauce_group_1
    strategy:
      max-parallel: 1
      matrix:
        python-version: [ '3.6', '3.11' ]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{inputs.ref || github.ref}}
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/download-artifact@v3
        with:
          name: packages
      - run: make eyes_appium_generated_tests
        working-directory: python
        env:
          APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
          APPLITOOLS_API_KEY_READ: ${{ secrets.APPLITOOLS_API_KEY_READ }}
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
          BONGO_REPORT_TESTS: false
      - uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: ${{ format('selenium_{0}_appium', matrix.python-version) }}
          path: | 
            python/tests/coverage/appium/coverage-test-report.xml
            python/tests/coverage/appium/meta.json

  generated-tests-selenium:
    needs: dist-build
    if: ${{ !(github.event_name == 'workflow_dispatch') || inputs.generated_tests }}
    strategy:
      fail-fast: false  # avoid cancelling one job if another fails
      matrix:
        python-version: [ '3.6', '3.11' ]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{inputs.ref || github.ref}}
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: latest
      - uses: actions/download-artifact@v3
        with:
          name: packages
      - run: make eyes_selenium_generated_tests
        working-directory: python
        env:
          APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
          APPLITOOLS_API_KEY_READ: ${{ secrets.APPLITOOLS_API_KEY_READ }}
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
          BONGO_REPORT_TESTS: false
          GH_TOKEN: ${{secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: ${{ format('selenium_{0}_selenium', matrix.python-version) }}
          path: | 
            python/tests/coverage/selenium/coverage-test-report.xml
            python/tests/coverage/selenium/meta.json

  generated-tests-playwright:
    needs: dist-build
    if: ${{ !(github.event_name == 'workflow_dispatch') || inputs.generated_tests }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{inputs.ref || github.ref}}
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/download-artifact@v3
        with:
          name: packages
      - run: make eyes_playwright_generated_tests
        working-directory: python
        env:
          APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
          APPLITOOLS_API_KEY_READ: ${{ secrets.APPLITOOLS_API_KEY_READ }}
          RELEASING_PACKAGE: ${{ inputs.releasing_package }}

  functional-tests:
    needs: dist-build
    if: ${{ !(github.event_name == 'workflow_dispatch') || inputs.functional_tests }}
    strategy:
      fail-fast: false  # avoid cancelling one job if another fails
      matrix:
        os: [ ubuntu-20.04, windows-latest ]
        python-version: [ '2.7', '3.6', '3.11' ]
        exclude:
          - os: windows-latest
            python-version: '2.7'
          - os: windows-latest
            python-version: '3.6'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{inputs.ref || github.ref}}
      - if: matrix.python-version == '2.7'
        run: sudo apt-get --yes install python2 virtualenv && virtualenv --python python2 --download venv
        working-directory: python
      - if: matrix.python-version != '2.7'
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/download-artifact@v3
        with:
          name: packages
      - name: make eyes_images_functional_tests
        shell: bash
        run: |
          [ ${{ matrix.python-version }} = 2.7 ] && source venv/bin/activate
          make eyes_images_functional_tests
        working-directory: python
        env:
          APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
      - name: make eyes_playwright_functional_tests
        shell: bash
        run: |
          [ ${{ matrix.python-version }} = 2.7 ] && source venv/bin/activate
          make eyes_playwright_functional_tests
        if: ${{ matrix.python-version == '3.11' }}
        working-directory: python
        env:
          APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
      - name: make eyes_selenium_functional_tests
        shell: bash
        run: |
          [ ${{ matrix.python-version }} = 2.7 ] && source venv/bin/activate
          make eyes_selenium_functional_tests
        working-directory: python
        env:
          APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}

  robot-framework-tests:
    needs: dist-build
    if: ${{ !(github.event_name == 'workflow_dispatch') || inputs.robotframework_tests }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{inputs.ref || github.ref}}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.6'
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/download-artifact@v3
        with:
          name: packages
      - run: make eyes_robotframework_functional_tests
        working-directory: python
        env:
          APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}

  sauce-robot-framework-tests:
    needs: dist-build
    if: ${{ !(github.event_name == 'workflow_dispatch') || inputs.robotframework_tests }}
    concurrency: sauce_group_2
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{inputs.ref || github.ref}}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.6'
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/download-artifact@v3
        with:
          name: packages
      - run: make eyes_robotframework_sauce_functional_tests
        working-directory: python
        env:
          APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
  report:
    needs:
      - unit-tests
      - unit-tests-alpine
      - installation-tests
      - generated-tests-appium
      - generated-tests-selenium
      - generated-tests-playwright
      - generated-tests-images
      - functional-tests
      - robot-framework-tests
      - sauce-robot-framework-tests
    if: ${{ always() && github.event_name == 'schedule' }}
    runs-on: ubuntu-20.04
    steps:
      - uses: slackapi/slack-github-action@v1.21.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.PYTHON_SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        with:
          payload: |
            {
              "text": "Python tests <https://github.com/applitools/eyes.sdk.javascript1/actions/runs/${{github.run_id}}|execution> report:\nUnit tests: ${{needs.unit-tests.result}}\nUnit tests (alpine): ${{needs.unit-tests-alpine.result}}\nInstallation tests: ${{needs.installation-tests.result}}\nGenerated images tests: ${{needs.generated-tests-images.result}}\nGenerated appium tests: ${{needs.generated-tests-appium.result}}\nGenerated selenium tests: ${{needs.generated-tests-selenium.result}}\nGenerated playwright tests: ${{needs.generated-tests-playwright.result}}\nFunctional tests: ${{needs.functional-tests.result}}\nRobot framework tests: ${{needs.robot-framework-tests.result}}\nRobot framework tests (sauce): ${{needs.sauce-robot-framework-tests.result}}"
            }